language: php

sudo: false

before_install:
    - composer self-update

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

matrix:
    fast_finish: true
    include:
        - php: 5.4
          env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'
    allow_failures:
        - php: 7.0

cache:
    directories:
        - $HOME/.composer/cache

install:
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

before_script:
    - [[ "$TRAVIS_PHP_VERSION" == "hhv*" ]] && cat .travis.ini >> /etc/hhvm/php.ini
    - [[ "$TRAVIS_PHP_VERSION" == "php*" ]] && phpenv config-add .travis.ini

script:
    - make tests
